# Generated by Django 3.0.7 on 2021-06-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210603_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcategory',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='pcolour',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='pcompany',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='premaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdesc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pprice',
            field=models.IntegerField(default=0),
        ),
    ]
