# Generated by Django 3.0.7 on 2021-06-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='premaining',
        ),
        migrations.AddField(
            model_name='order',
            name='order_track',
            field=models.CharField(default='onprocess', max_length=20),
        ),
    ]
